import {
  Scale, BookOpen, Droplets, Shield, Leaf, Zap, Sprout, Users, Heart, Activity, Coins, MapPin,
  TreePine, Bird, Brain, Waves, Building2,
  LucideIcon
} from 'lucide-react';

export interface Program {
  id: string;
  title: string;
  title_bn: string;
  icon: LucideIcon;
  theme: string;
  theme_bn: string;
  color: string;
  bg: string;
  description: string;
  description_bn: string;
  keyPrograms: string[];
  keyPrograms_bn: string[];
}

export const allPrograms: Program[] = [
  {
    id: 'climate-justice',
    title: 'Climate Justice & Environmental Advocacy',
    title_bn: 'জলবায়ু ন্যায়বিচার ও পরিবেশগত অ্যাডভোকেসি',
    icon: Scale,
    theme: 'Climate',
    theme_bn: 'জলবায়ু',
    color: '#1A6B3C',
    bg: '#E8F5EE',
    description: "YCN places climate justice at the heart of everything we do. Bangladesh is among the world's most climate-vulnerable nations — facing rising sea levels, cyclones, floods, salinity intrusion, and extreme heat — yet contributes less than 0.5% of global emissions. We advocate fiercely and unapologetically for the rights of affected communities.",
    description_bn: 'YCN জলবায়ু ন্যায়বিচারকে আমাদের সমস্ত কাজের কেন্দ্রে রাখে। বাংলাদেশ সমুদ্রপৃষ্ঠের উচ্চতা বৃদ্ধি, ঘূর্ণিঝড়, বন্যা, লবণাক্ততার অনুপ্রবেশ এবং চরম তাপপ্রবাহের মুখোমুখি — অথচ বৈশ্বিক নির্গমনে আমাদের অবদান ০.৫%-এরও কম। আমরা ক্ষতিগ্রস্থ জনগোষ্ঠীর অধিকারের জন্য অবিচলভাবে কথা বলি।',
    keyPrograms: [
      'Regional Climate Advocacy — Representing Bangladesh and South Asian youth at UN climate negotiations (UNFCCC/COP), Asia Pacific regional forums, and international environmental justice platforms.',
      'Environmental Legal Literacy — Educating communities on their environmental rights under national law and international frameworks.',
      'Biodiversity Conservation Campaigns — Community-based mangrove restoration, wetland protection, and biodiversity monitoring in the Sundarbans and coastal belt.',
      'Anti-Pollution Awareness — Campaigns targeting industrial pollution, plastic contamination, and air quality degradation.',
      'Climate Litigation Support — Assisting frontline communities in documenting climate harms for advocacy and legal proceedings.',
    ],
    keyPrograms_bn: [
      'আঞ্চলিক জলবায়ু অ্যাডভোকেসি — জাতিসংঘের জলবায়ু আলোচনা (UNFCCC/COP), এশিয়া প্যাসিফিক আঞ্চলিক ফোরাম এবং আন্তর্জাতিক পরিবেশগত ন্যায়বিচার প্ল্যাটফর্মগুলোতে বাংলাদেশ ও দক্ষিণ এশিয়ার যুবকদের প্রতিনিধিত্ব।',
      'পরিবেশগত আইনি সাক্ষরতা — জাতীয় আইন এবং আন্তর্জাতিক কাঠামোর অধীনে পরিবেশগত অধিকার সম্পর্কে সমাজকে শিক্ষিত করা।',
      'জীববৈচিত্র্য সংরক্ষণ অভিযান — সুন্দরবন এবং উপকূলীয় অঞ্চলে সামাজিক-ভিত্তিক ম্যানগ্রোভ পুনরুদ্ধার, জলাভূমি সুরক্ষা এবং জীববৈচিত্র্য পর্যবেক্ষণ।',
      'দূষণ বিরোধী সচেতনতা — শিল্প দূষণ, প্লাস্টিক দূষণ এবং বায়ুর মান হ্রাসকে লক্ষ্য করে প্রচারণা।',
      'জলবায়ু মামলা সহায়তা — অ্যাডভোকেসি এবং আইনি প্রক্রিয়ার জন্য জলবায়ুজনিত ক্ষয়ক্ষতি নথিবদ্ধ করতে ফ্রন্টলাইন সম্প্রদায়কে সহায়তা করা।',
    ],
  },
  {
    id: 'education',
    title: 'Education, Research & Knowledge Management',
    title_bn: 'শিক্ষা, গবেষণা ও জ্ঞান ব্যবস্থাপনা',
    icon: BookOpen,
    theme: 'Education',
    theme_bn: 'শিক্ষা',
    color: '#0E7490',
    bg: '#E0F7FA',
    description: 'Education is both a right and a tool for transformation. YCN builds climate literacy and critical thinking from the classroom to the community hall, while producing original research that informs national and regional policy.',
    description_bn: 'শিক্ষা একই সাথে অধিকার এবং পরিবর্তনের হাতিয়ার। YCN ক্লাসরুম থেকে কমিউনিটি হল পর্যন্ত জলবায়ু সচেতনতা ও যৌক্তিক চিন্তাভাবনা তৈরি করে, এবং জাতীয় ও আঞ্চলিক নীতি নির্ধারণে ভূমিকা রাখে এমন মৌলিক গবেষণা পরিচালনা করে।',
    keyPrograms: [
      'Climate & Environment Education in Schools — Integrating climate change modules into school curricula in partnership with local education boards.',
      'Youth Research Fellowship — Annual fellowships supporting young researchers to conduct community-based climate and environmental studies.',
      'Climate Research Assistance — Supporting academic institutions and NGOs with field data collection, community surveys, and participatory research.',
      'Knowledge Exchange Platform — Annual symposiums, publications, and digital platforms to share findings with policymakers and practitioners.',
      'Public Awareness Campaigns — Mass media, social media, and street campaigns on climate change, biodiversity, and environmental health.',
    ],
    keyPrograms_bn: [
      'বিদ্যালয়ে জলবায়ু ও পরিবেশ শিক্ষা — স্থানীয় শিক্ষা বোর্ডের সাথে অংশীদারিত্বে স্কুলের পাঠ্যসূচিতে জলবায়ু পরিবর্তনের মডিউল অন্তর্ভুক্ত করা।',
      'যুব গবেষণা ফেলোশিপ — তরুণ গবেষকদের সামাজিক-ভিত্তিক জলবায়ু এবং পরিবেশগত অধ্যয়ন পরিচালনা করতে বার্ষিক ফেলোশিপের সহায়তা।',
      'জলবায়ু গবেষণা সহায়তা — মাঠ পর্যায়ের তথ্য সংগ্রহ, সামাজিক সমীক্ষা এবং অংশগ্রহণমূলক গবেষণার মাধ্যমে শিক্ষা প্রতিষ্ঠান এবং এনজিওগুলোকে সহায়তা করা।',
      'জ্ঞান বিনিময় প্ল্যাটফর্ম — নীতিনির্ধারক এবং অনুশীলনকারীদের সাথে গবেষণার ফলাফল শেয়ার করার জন্য বার্ষিক সিম্পোজিয়াম, প্রকাশনা এবং ডিজিটাল প্ল্যাটফর্ম।',
      'জনসচেতনতা মূলক ক্যাম্পেইন — জলবায়ু পরিবর্তন, জীববৈচিত্র্য এবং পরিবেশগত স্বাস্থ্য নিয়ে গণমাধ্যম, সামাজিক যোগাযোগ মাধ্যম এবং সড়ক প্রচার।',
    ],
  },
  {
    id: 'wash',
    title: 'Water, Sanitation & Hygiene (WASH)',
    title_bn: 'পানি, স্যানিটেশন ও স্বাস্থ্যবিধি (WASH)',
    icon: Droplets,
    theme: 'Water',
    theme_bn: 'পানি',
    color: '#1565C0',
    bg: '#E3F2FD',
    description: "Safe water and dignified sanitation are non-negotiable human rights. Climate change is intensifying water stress across Bangladesh and the wider region, disproportionately harming women, children, and coastal communities. YCN's WASH programs deliver tangible, life-changing improvements in water security and sanitary conditions.",
    description_bn: 'নিরাপদ পানি এবং মর্যাদাপূর্ণ স্যানিটেশন মানুষের অবিচ্ছেদ্য অধিকার। জলবায়ু পরিবর্তন বাংলাদেশ ও সমগ্র অঞ্চলে পানির সংকটকে তীব্র করে তুলছে, যা নারী, শিশু এবং উপকূলীয় সম্প্রদায়ের জন্য মারাত্মক ক্ষতির কারণ হচ্ছে। YCN-এর WASH কার্যক্রম পানির নিরাপত্তা এবং স্বাস্থ্যকর ব্যবস্থার বাস্তব উন্নতি নিশ্চিত করছে।',
    keyPrograms: [
      'Safe Drinking Water Access — Installation and maintenance of arsenic-free tube wells, rainwater harvesting systems, and community water purification units.',
      'Sanitation Infrastructure — Construction of climate-resilient latrines and hygiene facilities in flood-prone and coastal areas.',
      'Menstrual Hygiene Management — Providing products, education, and safe facilities for girls and women in schools and communities.',
      'WASH in Schools — Ensuring every partner school meets minimum WASH standards.',
      'Community Hygiene Education — Behavior change communication on handwashing, open defecation-free communities, and waterborne disease prevention.',
    ],
    keyPrograms_bn: [
      'নিরাপদ খাবার পানির ব্যবস্থা — আর্সেনিকমুক্ত নলকূপ স্থাপন, বৃষ্টির পানি সংগ্রহ পদ্ধতি এবং সামাজিক পানি বিশুদ্ধকরণ ইউনিট স্থাপন ও রক্ষণাবেক্ষণ।',
      'স্যানিটেশন অবকাঠামো — বন্যাপ্রবণ এবং উপকূলীয় এলাকায় জলবায়ু-সহনশীল ল্যাট্রিন এবং স্বাস্থ্যবিধি সুবিধা নির্মাণ।',
      'ঋতুস্রাবের স্বাস্থ্যবিধি ব্যবস্থাপনা — স্কুল এবং সম্প্রদায়ে মেয়ে ও নারীদের জন্য পণ্য, শিক্ষা এবং নিরাপদ সুবিধা প্রদান।',
      'বিদ্যালয়ে ওয়াশ (WASH) — প্রতিটি অংশীদার বিদ্যালয় যাতে ন্যূনতম WASH মান পূরণ করে তা নিশ্চিত করা।',
      'সামাজিক স্বাস্থ্যবিধি শিক্ষা — হাত ধোয়া, উন্মুক্ত মলত্যাগ মুক্ত সমাজ এবং পানিবাহিত রোগ প্রতিরোধে আচরণ পরিবর্তনের প্রচারণা।',
    ],
  },
  {
    id: 'disaster-risk',
    title: 'Disaster Risk Management, Relief & Resilience',
    title_bn: 'দুর্যোগ ঝুঁকি ব্যবস্থাপনা, ত্রাণ ও সহনশীলতা',
    icon: Shield,
    theme: 'Disaster',
    theme_bn: 'দুর্যোগ',
    color: '#7B1FA2',
    bg: '#F3E5F5',
    description: 'Living on the frontlines of climate change means facing disasters with increasing frequency and intensity. YCN works with communities to anticipate, prepare, respond to, and recover from climate-induced disasters — building a culture of resilience rather than dependency.',
    description_bn: 'জলবায়ু পরিবর্তনের ফ্রন্টলাইনে বসবাসের অর্থ হলো ক্রমবর্ধমান তীব্রতা ও ফ্রিকোয়েন্সির সাথে দুর্যোগের মুখোমুখি হওয়া। YCN জলবায়ু-প্ররোচিত দুর্যোগের পূর্বাভাস, প্রস্তুতি, সাড়া দেওয়া এবং পুনরুদ্ধার করতে কাজ করে — যা পরনির্ভরশীলতার পরিবর্তে সহনশীলতার সংস্কৃতি গড়ে তোলে।',
    keyPrograms: [
      'Community Disaster Risk Reduction (DRR) Training — Training youth volunteers and community leaders in early warning systems, evacuation planning, and emergency response.',
      'Youth Disaster Response Teams — Rapid-response volunteer brigades equipped and trained for flood, cyclone, and storm surge emergencies.',
      'Relief Distribution — Coordinating timely distribution of food, clean water, medicines, and non-food items in disaster-affected areas.',
      'Post-Disaster Psychosocial Support — Providing mental health first aid and community counseling in the aftermath of disasters.',
      'Climate Risk Mapping — Participatory mapping of climate hazards and vulnerabilities at the community level to guide planning.',
    ],
    keyPrograms_bn: [
      'সামাজিক দুর্যোগ ঝুঁকি হ্রাস (DRR) প্রশিক্ষণ — প্রারম্ভিক সতর্কতা ব্যবস্থা, উচ্ছেদ পরিকল্পনা এবং জরুরি প্রতিক্রিয়ায় যুব স্বেচ্ছাসেবক ও সামাজিক নেতাদের প্রশিক্ষণ দেওয়া।',
      'যুব দুর্যোগ প্রতিক্রিয়া দল — বন্যা, ঘূর্ণিঝড় এবং জলোচ্ছ্বাস জরুরি অবস্থার জন্য সজ্জিত ও প্রশিক্ষিত দ্রুত-প্রতিক্রিয়া স্বেচ্ছাসেবক ব্রিগেড।',
      'ত্রাণ বিতরণ — দুর্যোগ-কবলিত এলাকায় খাদ্য, বিশুদ্ধ পানি, ওষুধ এবং অ-খাদ্য সামগ্রীর সময়মত বিতরণ সমন্বয় করা।',
      'দুর্যোগ পরবর্তী মনস্তাত্ত্বিক সহায়তা — দুর্যোগের পর মানসিক স্বাস্থ্য প্রাথমিক চিকিৎসা এবং সামাজিক কাউন্সেলিং প্রদান।',
      'জলবায়ু ঝুঁকি মানচিত্রকরণ — পরিকল্পনা গাইড করতে সামাজিক স্তরে জলবায়ু ঝুঁকি এবং দুর্বলতার অংশগ্রহণমূলক ম্যাপিং।',
    ],
  },
  {
    id: 'sustainable-livelihoods',
    title: 'Sustainable Livelihoods & Resilience-Based Agriculture',
    title_bn: 'টেকসই জীবিকা ও সহনশীলতা-ভিত্তিক কৃষি',
    icon: Leaf,
    theme: 'Livelihoods',
    theme_bn: 'জীবিকা',
    color: '#2E7D32',
    bg: '#E8F5E9',
    description: 'Climate change is destroying traditional livelihoods — sinking farmlands, increasing salinity, displacing fishing communities, and disrupting seasonal patterns. YCN helps affected communities transition to and strengthen climate-adaptive livelihoods and sustainable food systems.',
    description_bn: 'জলবায়ু পরিবর্তন ঐতিহ্যবাহী জীবিকাকে ধ্বংস করছে — কৃষিজমি তলিয়ে দেওয়া, লবণাক্ততা বৃদ্ধি, মৎস্যজীবী সম্প্রদায়কে বাস্তুচ্যুত করা এবং ঋতুভিত্তিক বৈচিত্র্যকে ব্যাহত করা। YCN ক্ষতিগ্রস্ত জনগোষ্ঠীকে জলবায়ু-অভিযোজিত জীবিকা এবং টেকসই খাদ্য ব্যবস্থায় রূপান্তর ও শক্তিশালী করতে সহায়তা করে।',
    keyPrograms: [
      'Resilience-Based Agriculture — Training farmers in climate-smart techniques including saline-tolerant crop varieties, raised-bed farming, floating gardens, and water-efficient irrigation.',
      'Alternative Livelihood Development — Supporting transitions from climate-vulnerable livelihoods (e.g., brackish water fishing, flood-prone subsistence farming) to diversified, sustainable income sources.',
      'Agroforestry & Food Security — Integrating trees into farming landscapes to improve food diversity, income, and ecosystem services.',
      'Market Linkage & Value Chains — Connecting smallholder farmers and producers with fair markets, cooperatives, and digital trading platforms.',
      'Homestead Gardening for Nutrition — Promoting kitchen gardens among women and households for nutritional security and income generation.',
    ],
    keyPrograms_bn: [
      'সহনশীলতা-ভিত্তিক কৃষি — লবণাক্ততা-সহনশীল ফসলের জাত, উraised-bed চাষাবাদ, ভাসমান বাগান এবং পানি-সাশ্রয়ী সেচ সহ জলবায়ু-স্মার্ট প্রযুক্তিতে কৃষকদের প্রশিক্ষণ দেওয়া।',
      'বিকল্প জীবিকা উন্নয়ন — জলবায়ু-ঝুঁকিপূর্ণ জীবিকা (যেমন লবণাক্ত পানির মাছ ধরা, বন্যাপ্রবণ জীবনধারণের কৃষি) থেকে বৈচিত্র্যময়, টেকসই আয়ের উৎসে রূপান্তরকে সমর্থন করা।',
      'কৃষি-বনায়ন এবং খাদ্য নিরাপত্তা — খাদ্যের বৈচিত্র্য, আয় এবং ইকোসিস্টেম পরিষেবাগুলো উন্নত করতে কৃষি ল্যান্ডস্কেপে গাছ একীভূত করা।',
      'বাজার সংযোগ ও মূল্য শৃঙ্খল — ক্ষুদ্র চাষী এবং উৎপাদকদের ন্যায্য বাজার, সমবায় এবং ডিজিটাল ট্রেডিং প্ল্যাটফর্মের সাথে সংযুক্ত করা।',
      'পুষ্টির জন্য বসতবাড়ি বাগান — পুষ্টি নিরাপত্তা এবং আয় বৃদ্ধির জন্য নারী ও পরিবারের মধ্যে রান্নাঘরের বাগান প্রচার করা।',
    ],
  },
  {
    id: 'renewable-energy',
    title: 'Renewable Energy & Waste Management',
    title_bn: 'নবায়নযোগ্য শক্তি ও বর্জ্য ব্যবস্থাপনা',
    icon: Zap,
    theme: 'Energy',
    theme_bn: 'জ্বালানি',
    color: '#F57F17',
    bg: '#FFF8E1',
    description: "Bangladesh's energy future must be clean, affordable, and just. YCN promotes renewable energy access in underserved communities while tackling the growing crisis of plastic and electronic waste threatening ecosystems and human health.",
    description_bn: 'বাংলাদেশের জ্বালানি ভবিষ্যৎ অবশ্যই পরিষ্কার, সাশ্রয়ী এবং ন্যায্য হতে হবে। YCN সুবিধাবঞ্চিত সম্প্রদায়গুলোতে নবায়নযোগ্য শক্তির প্রচার করে এবং একই সাথে প্লাস্টিক ও ইলেকট্রনিক বর্জ্যের ক্রমবর্ধমান সংকটের সমাধান করে যা বাস্তুতন্ত্র ও মানুষের স্বাস্থ্যের জন্য হুমকি সৃষ্টি করছে।',
    keyPrograms: [
      'Solar Energy for Rural Communities — Facilitating access to solar home systems, solar-powered irrigation, and mini-grids for off-grid households and institutions.',
      'Biogas Programs — Supporting biogas digester installation for clean cooking and organic waste management in rural households.',
      'Plastic Waste Reduction Campaigns — Community-based campaigns and school programs targeting single-use plastic elimination.',
      'Community Waste Management Systems — Supporting local governments and communities to establish segregated waste collection and composting systems.',
      'E-Waste Awareness — Education and safe disposal campaigns for electronic waste in urban and peri-urban areas.',
    ],
    keyPrograms_bn: [
      'গ্রামীণ সম্প্রদায়ের জন্য সৌর শক্তি — বিদ্যুৎ-বিহীন পরিবার এবং প্রতিষ্ঠানের জন্য সোলার হোম সিস্টেম, সৌর-চালিত সেচ এবং মিনি-গ্রিডের সুবিধা প্রদান।',
      'বায়োগ্যাস কার্যক্রম — গ্রামীণ পরিবারে পরিষ্কার রান্না এবং জৈব বর্জ্য ব্যবস্থাপনার জন্য বায়োগ্যাস ডাইজেস্টার স্থাপনে সহায়তা।',
      'প্লাস্টিক বর্জ্য হ্রাস অভিযান — একবার ব্যবহারযোগ্য প্লাস্টিক বর্জনের লক্ষ্যে সামাজিক-ভিত্তিক প্রচারণা এবং স্কুল প্রোগ্রাম।',
      'সামাজিক বর্জ্য ব্যবস্থাপনা ব্যবস্থা — পৃথক বর্জ্য সংগ্রহ এবং কম্পোস্টিং সিস্টেম স্থাপনের জন্য স্থানীয় সরকার ও সম্প্রদায়কে সহায়তা করা।',
      'ই-বর্জ্য সচেতনতা — শহর ও শহরতলী এলাকায় ইলেকট্রনিক বর্জ্যের জন্য শিক্ষা এবং নিরাপদ নিষ্কাশন প্রচারণা।',
    ],
  },
  {
    id: 'tree-plantation',
    title: 'Tree Plantation & Ecosystem Restoration',
    title_bn: 'বৃক্ষরোপণ ও বাস্তুতন্ত্র পুনরুদ্ধার',
    icon: Sprout,
    theme: 'Ecosystem',
    theme_bn: 'বাস্তুতন্ত্র',
    color: '#1A6B3C',
    bg: '#E8F5EE',
    description: "Trees are among nature's most powerful climate solutions. YCN's tree plantation programs combine ecological restoration with community empowerment, creating green infrastructure that benefits both the environment and livelihoods.",
    description_bn: 'বৃক্ষ প্রকৃতির সবচেয়ে শক্তিশালী জলবায়ু সমাধানের একটি। YCN-এর বৃক্ষরোপণ কর্মসূচি পরিবেশগত পুনরুদ্ধারের সাথে সামাজিক ক্ষমতায়নকে একত্রিত করে, সবুজ অবকাঠামো তৈরি করে যা পরিবেশ ও জীবিকা উভয়ের জন্যই উপকারী।',
    keyPrograms: [
      'National and Regional Tree Plantation Drives — Annual campaigns planting native, climate-resilient tree species across schools, roadsides, riverbanks, and degraded lands.',
      'Mangrove Restoration — Community-led mangrove replanting in the Sundarbans buffer zone and coastal embankments for storm protection and carbon sequestration.',
      'Urban Greening — School and community urban greening projects in cities to reduce heat island effects and improve air quality.',
      'Social Forestry — Supporting community ownership and management of planted forests for sustainable livelihoods.',
    ],
    keyPrograms_bn: [
      'জাতীয় ও আঞ্চলিক বৃক্ষরোপণ অভিযান — স্কুল, রাস্তার পাশে, নদীর তীরে এবং ক্ষয়প্রাপ্ত জমিতে দেশীয় ও জলবায়ু-সহনশীল গাছের প্রজাতি রোপণের বার্ষিক প্রচারণা।',
      'ম্যানগ্রোভ পুনরুদ্ধার — ঝড় থেকে সুরক্ষা এবং কার্বন নিঃসরণ হ্রাসের জন্য সুন্দরবনের বাফার জোন এবং উপকূলীয় বাঁধে সামাজিক-নেতৃত্বাধীন ম্যানগ্রোভ রোপণ।',
      'নগর সবুজায়ন — শহরের উত্তাপের প্রভাব কমাতে এবং বায়ুর মান উন্নত করতে স্কুল ও সামাজিক নগর সবুজায়ন প্রকল্প।',
      'সামাজিক বনায়ন — টেকসই জীবিকার জন্য রোপণকৃত বনের সামাজিক মালিকানা এবং ব্যবস্থাপনায় সহায়তা করা।',
    ],
  },
  {
    id: 'youth-development',
    title: 'Youth Capacity Development & Leadership',
    title_bn: 'যুব দক্ষতা উন্নয়ন ও নেতৃত্ব',
    icon: Users,
    theme: 'Youth',
    theme_bn: 'যুবসমাজ',
    color: '#6A1B9A',
    bg: '#F3E5F5',
    description: 'YCN invests deeply in building the next generation of climate leaders. We believe that young people equipped with skills, knowledge, and networks can drive systemic change in their communities and beyond.',
    description_bn: 'YCN পরবর্তী প্রজন্মের জলবায়ু নেতাদের তৈরিতে গভীরভাবে বিনিয়োগ করে। আমরা বিশ্বাস করি যে দক্ষতা, জ্ঞান এবং নেটওয়ার্কের সাথে সজ্জিত তরুণরা তাদের সমাজ এবং এর বাইরেও নিয়মতান্ত্রিক পরিবর্তন আনতে পারে।',
    keyPrograms: [
      'Youth Leadership Academy — Intensive multi-module leadership training program for young activists, community organizers, and emerging leaders.',
      'Climate Negotiation & Advocacy Training — Preparing youth delegates for participation in national and international climate forums.',
      'Vocational & Skills Training — Technical and vocational education in renewable energy, sustainable agriculture, environmental monitoring, and social work.',
      'Digital Skills & Communication — Training young people in digital advocacy, social media campaigning, data visualization, and online journalism.',
      'Volunteer Management Program — Structured volunteerism with training, recognition, and pathways to professional development.',
    ],
    keyPrograms_bn: [
      'যুব নেতৃত্ব একাডেমি — তরুণ কর্মী, সামাজিক সংগঠক এবং উদীয়মান নেতাদের জন্য নিবিড় বহু-মডিউল নেতৃত্ব প্রশিক্ষণ কার্যক্রম।',
      'জলবায়ু আলোচনা ও অ্যাডভোকেসি প্রশিক্ষণ — জাতীয় ও আন্তর্জাতিক জলবায়ু ফোরামে অংশগ্রহণের জন্য যুব প্রতিনিধিদের প্রস্তুত করা।',
      'বৃত্তিমূলক ও দক্ষতা প্রশিক্ষণ — নবায়নযোগ্য শক্তি, টেকসই কৃষি, পরিবেশগত পর্যবেক্ষণ এবং সমাজকর্মে কারিগরি ও বৃত্তিমূলক শিক্ষা।',
      'ডিজিটাল দক্ষতা ও যোগাযোগ — ডিজিটাল অ্যাডভোকেসি, সামাজিক মিডিয়া প্রচারণা, ডেটা ভিজ্যুয়ালাইজেশন এবং অনলাইন সাংবাদিকতায় তরুণদের প্রশিক্ষণ।',
      'স্বেচ্ছাসেবক ব্যবস্থাপনা কার্যক্রম — প্রশিক্ষণ, স্বীকৃতি এবং পেশাদার বিকাশের পথ সহ কাঠামোগত স্বেচ্ছাসেবক কার্যক্রম।',
    ],
  },
  {
    id: 'women-empowerment',
    title: 'Women Empowerment & Gender Equality',
    title_bn: 'নারী ক্ষমতায়ন ও জেন্ডার সমতা',
    icon: Heart,
    theme: 'Gender',
    theme_bn: 'জেন্ডার',
    color: '#C2185B',
    bg: '#FCE4EC',
    description: "Climate change is not gender-neutral. Women and girls in Bangladesh face heightened climate risks, from increased domestic burden during disasters to loss of income, sexual violence in displacement, and exclusion from decision-making. YCN's gender programming is transformative and intersectional.",
    description_bn: 'জলবায়ু পরিবর্তন জেন্ডার-নিরপেক্ষ নয়। বাংলাদেশের নারী ও মেয়েরা বর্ধিত জলবায়ু ঝুঁকির সম্মুখীন হয়, দুর্যোগের সময় অতিরিক্ত পারিবারিক কাজ থেকে শুরু করে আয় হারানো, স্থানান্তরের সময় সহিংসতা এবং সিদ্ধান্ত গ্রহণ থেকে বাদ পড়া। YCN-এর জেন্ডার কর্মসূচি রূপান্তরমূলক এবং আন্তঃবিভাগীয়।',
    keyPrograms: [
      "Women's Climate Leadership Program — Building the capacity of women to lead climate action in their communities and beyond.",
      "Women's Livelihood Groups — Forming and supporting women's self-help groups for climate-adaptive enterprise and savings.",
      'Gender-Based Violence Prevention — Awareness and response programming in disaster-affected and vulnerable communities.',
      "Girls' Education & Retention — Scholarships, mentoring, and community engagement to keep girls in school, particularly in climate-affected areas.",
      'Women in Governance — Advocacy for meaningful representation of women in local government, disaster committees, and environmental bodies.',
    ],
    keyPrograms_bn: [
      'নারীদের জলবায়ু নেতৃত্ব কার্যক্রম — সমাজ ও এর বাইরে জলবায়ু পদক্ষেপে নেতৃত্ব দেওয়ার জন্য নারীদের সক্ষমতা তৈরি করা।',
      'নারীদের জীবিকা গোষ্ঠী — জলবায়ু-অভিযোজিত এন্টারপ্রাইজ এবং সঞ্চয়ের জন্য নারীদের স্বনির্ভর দল গঠন ও সমর্থন করা।',
      'জেন্ডার-ভিত্তিক সহিংসতা প্রতিরোধ — দুর্যোগ-আক্রান্ত এবং ঝুঁকিপূর্ণ সম্প্রদায়গুলোতে সচেতনতা এবং প্রতিক্রিয়া কর্মসূচি।',
      'মেয়েদের শিক্ষা ও ধরে রাখা — বিশেষ করে জলবায়ু-আক্রান্ত এলাকায় মেয়েদের স্কুলে ধরে রাখার জন্য বৃত্তি, মেন্টরিং এবং সামাজিক সম্পৃক্ততা।',
      'পরিচালনায় নারী — স্থানীয় সরকার, দুর্যোগ কমিটি এবং পরিবেশগত সংস্থায় নারীদের অর্থপূর্ণ প্রতিনিধিত্বের জন্য অ্যাডভোকেসি।',
    ],
  },
  {
    id: 'social-harmony',
    title: 'Social Harmony & Community Cohesion',
    title_bn: 'সামাজিক সম্প্রীতি ও সামাজিক সংহতি',
    icon: Users,
    theme: 'Community',
    theme_bn: 'কমিউনিটি',
    color: '#D97706',
    bg: '#FFF8E1',
    description: 'Climate stress can intensify social tensions — over land, water, resources, and migration. YCN promotes social cohesion, interfaith harmony, and inclusive community development as essential foundations for resilience.',
    description_bn: 'জলবায়ু চাপ সামাজিক উত্তেজনা তীব্র করতে পারে — জমি, পানি, সম্পদ এবং অভিবাসন নিয়ে। YCN সামাজিক সংহতি, আন্তঃধর্মীয় সম্প্রীতি এবং অন্তর্ভুক্তিমূলক সামাজিক উন্নয়নকে সহনশীলতার প্রয়োজনীয় ভিত্তি হিসেবে প্রচার করে।',
    keyPrograms: [
      'Interfaith Climate Dialogues — Bringing together religious and community leaders to build shared values around environmental stewardship.',
      'Youth Civic Engagement — Mobilizing young people in local governance, community decision-making, and social accountability processes.',
      'Conflict-Sensitive Programming — Ensuring all YCN programs apply do-no-harm principles and contribute positively to social cohesion.',
      'Cultural Programs for Climate Awareness — Using art, theater, music, and storytelling to communicate climate messages and celebrate community resilience.',
    ],
    keyPrograms_bn: [
      'আন্তঃধর্মীয় জলবায়ু সংলাপ — পরিবেশগত স্টুয়ার্ডশিপের চারপাশে ভাগ করা মূল্যবোধ গড়ে তোলার জন্য ধর্মীয় এবং সামাজিক নেতাদের একত্রিত করা।',
      'যুব নাগরিক সম্পৃক্ততা — স্থানীয় শাসন, সামাজিক সিদ্ধান্ত গ্রহণ এবং সামাজিক জবাবদিহিতা প্রক্রিয়াগুলোতে যুবকদের একত্রিত করা।',
      'দ্বন্দ্ব-সংবেদনশীল প্রোগ্রামিং — নিশ্চিত করা যে সমস্ত YCN প্রোগ্রাম ক্ষতিকর নয় এমন নীতিগুলো প্রয়োগ করে এবং সামাজিক সংহতিতে ইতিবাচক অবদান রাখে।',
      'জলবায়ু সচেতনতার জন্য সাংস্কৃতিক কার্যক্রম — জলবায়ু বার্তা পৌঁছে দিতে এবং সামাজিক সহনশীলতা উদযাপনের জন্য শিল্প, থিয়েটার, সঙ্গীত এবং গল্প বলার ব্যবহার।',
    ],
  },
  {
    id: 'health-nutrition',
    title: 'Health, Nutrition & Community Well-being',
    title_bn: 'স্বাস্থ্য, পুষ্টি ও সামাজিক কল্যাণ',
    icon: Activity,
    theme: 'Health',
    theme_bn: 'স্বাস্থ্য',
    color: '#C2185B',
    bg: '#FCE4EC',
    description: "Climate change is a health crisis. Flooding, heat waves, salinity intrusion, and displacement are driving surges in waterborne disease, malnutrition, mental illness, and maternal mortality across Bangladesh. YCN's health programming brings frontline preventive care and health education directly to vulnerable communities — particularly women, children, and the ultra-poor.",
    description_bn: 'জলবায়ু পরিবর্তন একটি স্বাস্থ্য সংকট। বন্যা, তাপপ্রবাহ, লবণাক্ততার অনুপ্রবেশ এবং বাস্তুচ্যুতি বাংলাদেশের পানিবাহিত রোগ, অপুষ্টি, মানসিক অসুস্থতা এবং মাতৃমৃত্যুর হার বৃদ্ধি করছে। YCN-এর স্বাস্থ্য কর্মসূচি ফ্রন্টলাইন প্রতিরোধমূলক যত্ন এবং স্বাস্থ্য শিক্ষা সরাসরি ঝুঁকিপূর্ণ সম্প্রদায়ের কাছে নিয়ে আসে — বিশেষ করে নারী, শিশু এবং অতি-দরিদ্রদের জন্য।',
    keyPrograms: [
      'Community Health Volunteer Network — Training and deploying community health volunteers for household visits, health education, and disease surveillance in program areas.',
      'Maternal & Child Health — Antenatal care awareness, safe delivery promotion, immunization support, and newborn care education for mothers in climate-vulnerable communities.',
      'Nutrition Programs — Addressing malnutrition among children under 5 and pregnant/lactating mothers through supplementation, dietary education, and kitchen garden promotion.',
      'Adolescent Health & Reproductive Rights — Age-appropriate sexual and reproductive health education for adolescent girls and boys, including menstrual health, family planning awareness, and safe spaces.',
      'Mental Health & Psychosocial Support — Community-based mental health first aid, stigma reduction campaigns, and referral systems for survivors of disasters, violence, and displacement.',
      'Climate & Health Awareness — Community campaigns linking climate change to health outcomes — heatstroke, dengue, cholera, arsenic contamination — and building health-protective behaviors.',
      'Disability-Inclusive Health — Ensuring people with disabilities access health services without discrimination, with targeted outreach and reasonable accommodation.',
    ],
    keyPrograms_bn: [
      'সামাজিক স্বাস্থ্য স্বেচ্ছাসেবক নেটওয়ার্ক — কর্মসূচী এলাকায় গৃহ পরিদর্শন, স্বাস্থ্য শিক্ষা এবং রোগ নজরদারির জন্য সামাজিক স্বাস্থ্য স্বেচ্ছাসেবকদের প্রশিক্ষণ এবং মোতায়েন।',
      'মাতৃ ও শিশু স্বাস্থ্য — জলবায়ু-ঝুঁকিপূর্ণ সম্প্রদায়ে মায়েদের জন্য প্রসবপূর্ব যত্নের সচেতনতা, নিরাপদ প্রসবের প্রচার, টিকাদান সহায়তা এবং নবজাতকের যত্নের শিক্ষা।',
      'পুষ্টি কার্যক্রম — সম্পূরক খাদ্য, খাদ্য সংক্রান্ত শিক্ষা এবং রান্নাঘরের বাগান প্রচারের মাধ্যমে ৫ বছরের কম বয়সী শিশু এবং গর্ভবতী/স্তন্যদানকারী মায়েদের অপুষ্টি দূর করা।',
      'কৈশোরের স্বাস্থ্য ও প্রজনন অধিকার — বয়ঃসন্ধিকালীন মেয়ে ও ছেলেদের জন্য বয়স-উপযুক্ত যৌন ও প্রজনন স্বাস্থ্য শিক্ষা, যার মধ্যে রয়েছে মাসিকের স্বাস্থ্যবিধি, পরিবার পরিকল্পনা সচেতনতা এবং নিরাপদ স্থান।',
      'মানসিক স্বাস্থ্য ও মনস্তাত্ত্বিক সহায়তা — দুর্যোগ, সহিংসতা এবং বাস্তুচ্যুতির শিকার মানুষের জন্য সামাজিক-ভিত্তিক মানসিক স্বাস্থ্য প্রাথমিক চিকিৎসা, কুসংস্কার হ্রাস প্রচারণা এবং রেফারেল ব্যবস্থা।',
      'জলবায়ু ও স্বাস্থ্য সচেতনতা — জলবায়ু পরিবর্তনের সাথে স্বাস্থ্যের ফলাফলের সংযোগকারী সামাজিক প্রচারণা — হিটস্ট্রোক, ডেঙ্গু, cholera, আর্সেনিক দূষণ — এবং স্বাস্থ্য-সুরক্ষামূলক আচরণ তৈরি করা।',
      'প্রতিবন্ধী-অন্তর্ভুক্ত স্বাস্থ্য — লক্ষ্যযুক্ত প্রচার এবং যুক্তিসঙ্গত বাসস্থানের মাধ্যমে প্রতিবন্ধী ব্যক্তিরা যাতে বৈсем্য ছাড়াই স্বাস্থ্য পরিষেবাগুলো অ্যাক্সেস করতে পারে তা নিশ্চিত করা।',
    ],
  },
  {
    id: 'financial-inclusion',
    title: 'Financial Inclusion & Ultra-Poor Graduation',
    title_bn: 'আর্থিক অন্তর্ভুক্তি ও অতি-দরিদ্র গ্র্যাজুয়েশন',
    icon: Coins,
    theme: 'Finance',
    theme_bn: 'অর্থায়ন',
    color: '#D97706',
    bg: '#FFF8E1',
    description: "Poverty and climate vulnerability are deeply intertwined. Communities on the frontlines of climate change are often also the most economically marginalized — excluded from formal financial systems, unable to absorb shocks, and trapped in cycles of debt and destitution. YCN's financial inclusion and graduation programming provides a structured pathway out of extreme poverty, combining asset transfer, skills training, savings, and social support.",
    description_bn: 'দারিদ্র্য এবং জলবায়ু ঝুঁকি গভীরভাবে জড়িত। জলবায়ু পরিবর্তনের ফ্রন্টলাইনে থাকা সম্প্রদায়গুলো প্রায়শই অর্থনৈতিকভাবে সবচেয়ে বেশি প্রান্তিক — আনুষ্ঠানিক আর্থিক ব্যবস্থা থেকে বাদ পড়ে, ধাক্কা সামলাতে অক্ষম এবং ঋণের চক্রে আটকা পড়ে। YCN-এর আর্থিক অন্তর্ভুক্তি কার্যক্রম চরম দারিদ্র্য থেকে উত্তরণের একটি কাঠামোগত পথ প্রদান করে, যা সম্পদ হস্তান্তর, দক্ষতা প্রশিক্ষণ, সঞ্চয় এবং সামাজিক সহায়তাকে একত্রিত করে।',
    keyPrograms: [
      'Ultra-Poor Graduation Program — A time-bound, sequenced intervention combining asset transfer (productive assets such as livestock, seeds, or tools), business skills training, savings facilitation, healthcare linkage, and regular mentoring — enabling the ultra-poor to graduate to stable, dignified livelihoods.',
      'Savings Groups & Village Organizations — Forming community savings and credit groups, particularly for women, enabling access to low-interest credit for productive investments and emergency needs.',
      'Financial Literacy Training — Educating community members on budgeting, savings, loan management, and protection from predatory lending and money laundering.',
      'Linkage to Formal Finance — Connecting graduates and program participants to mobile banking (bKash, Nagad), government social safety nets, and formal financial institutions.',
      'Youth Entrepreneurship Fund — Small grants and mentoring for young entrepreneurs developing climate-smart businesses and social enterprises in underserved communities.',
      'Social Enterprise Development — Supporting youth-led social enterprises that address local climate and development needs while generating sustainable income for reinvestment in community programs.',
    ],
    keyPrograms_bn: [
      'চরম-দরিদ্র গ্র্যাজুয়েশন কার্যক্রম — একটি সময়সীমাবদ্ধ, ক্রমানুসারে সাজানো হস্তক্ষেপ যা সম্পদ হস্তান্তর (গবাদি পশু, বীজ বা যন্ত্রপাতির মতো উত্পাদনশীল সম্পদ), ব্যবসায়িক দক্ষতা প্রশিক্ষণ, সঞ্চয় সুবিধা, স্বাস্থ্যসেবা সংযোগ এবং নিয়মিত মেন্টরিং একত্রিত করে — যা অতি-দরিদ্রদের স্থিতিশীল ও মর্যাদাপূর্ণ জীবিকায় উন্নীত হতে সক্ষম করে।',
      'সঞ্চয় দল এবং গ্রাম সংগঠন — বিশেষ করে নারীদের জন্য সামাজিক সঞ্চয় ও ঋণ গ্রুপ গঠন করা, যা উত্পাদনশীল বিনিয়োগ এবং জরুরী প্রয়োজনের জন্য কম সুদে ঋণ অ্যাক্সেস করতে সক্ষম করে।',
      'আর্থিক সাক্ষরতা প্রশিক্ষণ — বাজেট, সঞ্চয়, ঋণ ব্যবস্থাপনা এবং শিকারী ঋণদান ও মানি লন্ডারিং থেকে সুরক্ষা বিষয়ে সামাজিক সদস্যদের শিক্ষিত করা।',
      'আনুষ্ঠানিক অর্থের সাথে সংযোগ — গ্র্যাজুয়েট ও কার্যক্রমের অংশগ্রহণকারীদের মোবাইল ব্যাংকিং (বিকাশ, নগদ), সরকারি সামাজিক নিরাপত্তা বেষ্টনী এবং আনুষ্ঠানিক আর্থিক প্রতিষ্ঠানের সাথে সংযুক্ত করা।',
      'যুব উদ্যোক্তা তহবিল — সুবিধাবঞ্চিত সম্প্রদায়গুলোতে জলবায়ু-স্মার্ট ব্যবসা এবং সামাজিক উদ্যোগের উন্নয়নকারী তরুণ উদ্যোক্তাদের জন্য ছোট অনুদান এবং মেন্টরিং।',
      'সামাজিক উদ্যোগ উন্নয়ন — স্থানীয় জলবায়ু এবং উন্নয়নের চাহিদা পূরণকারী যুব-নেতৃত্বাধীন সামাজিক উদ্যোগগুলোকে সমর্থন করা এবং একই সাথে পুনরায় বিনিয়োগের জন্য টেকসই আয় তৈরি করা।',
    ],
  },
  {
    id: 'legal-aid',
    title: 'Legal Aid, Human Rights & Social Justice',
    title_bn: 'আইনি সহায়তা, মানবাধিকার ও সামাজিক ন্যায়বিচার',
    icon: Scale,
    theme: 'Justice',
    theme_bn: 'ন্যায়বিচার',
    color: '#1A6B3C',
    bg: '#E8F5EE',
    description: 'Climate justice cannot be achieved without legal justice. Across Bangladesh, vulnerable communities — particularly women, minorities, indigenous peoples, and persons with disabilities — face land dispossession, discrimination, exploitation, and denial of rights in the context of climate displacement and environmental degradation. YCN provides legal literacy, rights-based education, and advocacy support to empower communities to claim and defend their rights.',
    description_bn: 'আইনি ন্যায়বিচার ছাড়া জলবায়ু ন্যায়বিচার অর্জন করা যায় না। বাংলাদেশ জুড়ে, ঝুঁকিপূর্ণ সম্প্রদায়গুলো — বিশেষ করে নারী, সংখ্যালঘু, আদিবাসী এবং প্রতিবন্ধী ব্যক্তিরা — জলবায়ু বাস্তুচ্যুতি এবং পরিবেশগত অবক্ষয়ের প্রেক্ষাপটে ভূমি দখল, বৈষম্য, শোষণ এবং অধিকার অস্বীকারের সম্মুখীন হয়। YCN আইনি সাক্ষরতা, অধিকার-ভিত্তিক শিক্ষা এবং অ্যাডভোকেসি সহায়তা প্রদান করে সম্প্রদায়গুলোকে তাদের অধিকার দাবি ও রক্ষায় ক্ষমতায়িত করে।',
    keyPrograms: [
      "Legal Literacy Campaigns — Community workshops on land rights, women's rights under family and inheritance law, labor rights, and rights of climate-displaced persons.",
      'Human Rights Documentation — Supporting communities in documenting rights violations, environmental harm, and climate injustice for advocacy and legal proceedings.',
      'Access to Justice — Facilitating referrals to legal aid organizations and pro-bono lawyers for community members facing land grabbing, domestic violence, child marriage, and other violations.',
      'Child Rights & Child Protection — Awareness and reporting mechanisms for child labor, child marriage, trafficking, and violence against children in climate-stressed communities.',
      'Anti-Discrimination & Inclusion Advocacy — Advocacy for the rights of indigenous communities, char-land populations, and other marginalized groups facing structural exclusion.',
      'Community Accountability Platforms — Supporting local social accountability mechanisms including citizen scorecards and community monitoring of public services and disaster relief.',
    ],
    keyPrograms_bn: [
      'আইনি সাক্ষরতা অভিযান — ভূমির অধিকার, পারিবারিক ও উত্তরাধিকার আইনের অধীনে নারীর অধিকার, শ্রম অধিকার এবং জলবায়ু-বাস্তুচ্যুত ব্যক্তিদের অধিকার বিষয়ে সামাজিক কর্মশালা।',
      'মানবাধিকার নথিবদ্ধকরণ — অ্যাডভোকেসি এবং আইনি প্রক্রিয়ার জন্য অধিকার লঙ্ঘন, পরিবেশগত ক্ষতি এবং জলবায়ুগত অন্যায় নথিবদ্ধ করতে সম্প্রদায়কে সহায়তা করা।',
      'ন্যায়বিচারে প্রবেশাধিকার — ভূমি দখল, পারিবারিক সহিংসতা, বাল্যবিয়ে এবং অন্যান্য লঙ্ঘনের মুখোমুখি হওয়া সামাজিক সদস্যদের জন্য আইনি সহায়তা সংস্থা এবং প্রো-বোনো আইনজীবীদের কাছে রেফারেলের সুবিধা দেওয়া।',
      'শিশু অধিকার ও শিশু সুরক্ষা — জলবায়ু-পীড়িত সম্প্রদায়গুলোতে শিশুশ্রম, বাল্যবিয়ে, পাচার এবং শিশুদের বিরুদ্ধে সহিংসতার জন্য সচেতনতা এবং রিপোর্টিং ব্যবস্থা।',
      'বৈষম্যবিরোধী ও অন্তর্ভুক্তি অ্যাডভোকেসি — আদিবাসী সম্প্রদায়, চরাঞ্চলের জনগোষ্ঠী এবং কাঠামোগত বর্জনের সম্মুখীন অন্যান্য প্রান্তিক গোষ্ঠীর অধিকারের জন্য অ্যাডভোকেসি।',
      'সামাজিক जवाबদেহিতা প্ল্যাটফর্ম — সিটিজেন স্কোরকার্ড এবং জনসেবা ও দুর্যোগ ত্রাণের সামাজিক তদারকি সহ স্থানীয় সামাজিক जवाबদিহিতা ব্যবস্থাকে সমর্থন করা।',
    ],
  },
  {
    id: 'climate-migration',
    title: 'Climate Migration, Displacement & Refugees',
    title_bn: 'জলবায়ু অভিবাসন, বাস্তুচ্যুতি ও শরণার্থী',
    icon: MapPin,
    theme: 'Migration',
    theme_bn: 'অভিবাসন',
    color: '#0E7490',
    bg: '#E0F7FA',
    description: 'Bangladesh is at the epicenter of climate-induced displacement. Millions are already internally displaced due to riverbank erosion, flooding, and sea-level rise, and projections suggest tens of millions more may be forced to move by 2050. YCN addresses the rights, dignity, and resilience of climate migrants and displaced communities — both those compelled to move and those left behind.',
    description_bn: 'বাংলাদেশ জলবায়ু-প্ররোচিত বাস্তুচ্যুতির কেন্দ্রবিন্দুতে রয়েছে। নদীভাঙন, বন্যা এবং সমুদ্রপৃষ্ঠের উচ্চতা বৃদ্ধির কারণে ইতিমধ্যে লক্ষ লক্ষ মানুষ অভ্যন্তরীণভাবে বাস্তুচ্যুত হয়েছে এবং ২০৫০ সালের মধ্যে আরও কোটি কোটি মানুষ বাস্তুচ্যুত হতে পারে। YCN জলবায়ু অভিবাসী এবং বাস্তুচ্যুত সম্প্রদায়ের অধিকার, মর্যাদা এবং সহনশীলতা নিয়ে কাজ করে — যারা চলে যেতে বাধ্য হয়েছে এবং যারা পিছনে রয়ে গেছে উভয়ই।',
    keyPrograms: [
      'Climate Migration Mapping — Participatory documentation of migration patterns, drivers, and community impacts in climate hotspot areas including coastal belts, char lands, and haor regions.',
      'Rights of the Displaced — Education and advocacy on the rights of internally displaced persons (IDPs), including access to shelter, education, healthcare, and livelihood entitlements.',
      'Safe Migration Awareness — Information and orientation for youth and families considering migration, covering safe routes, legal status, rights at destination, and responsible remittance management.',
      'Support for Receiving Communities — Programming to strengthen social cohesion, resource sharing, and equitable service access in urban and peri-urban areas receiving climate migrants.',
      "Regional Advocacy on Climate Mobility — Representing Bangladesh's climate displacement crisis in South Asian and Asia Pacific forums, advocating for a just regional framework on climate mobility and refugee protection.",
    ],
    keyPrograms_bn: [
      'জলবায়ু অভিবাসন মানচিত্রকরণ — উপকূলীয় অঞ্চল, চরাঞ্চল এবং হাওর অঞ্চল সহ জলবায়ু হটস্পট অঞ্চলগুলোতে অভিবাসন ধরণ, চালিকাশক্তি এবং সামাজিক প্রভাবগুলোর অংশগ্রহণমূলক ডকুমেন্টেশন।',
      'বাস্তুচ্যুতদের অধিকার — অভ্যন্তরীণভাবে বাস্তুচ্যুত ব্যক্তিদের (IDPs) অধিকার সম্পর্কিত শিক্ষা এবং অ্যাডভোকেসি, যার মধ্যে রয়েছে আশ্রয়, শিক্ষা, স্বাস্থ্যсеবা এবং জীবিকার সুযোগ।',
      'নিরাপদ অভিবাসন সচেতনতা — নিরাপদ রুট, আইনি মর্যাদা, গন্তব্যে অধিকার এবং দায়িত্বশীল রেমিট্যান্স ব্যবস্থাপনার বিষয়গুলো কভার করে অভিবাসন বিবেচনাধীন যুব ও পরিবারগুলোর জন্য তথ্য ও ওরিয়েন্টেশন।',
      'সুইকারী সম্প্রদায়ের জন্য সহায়তা — জলবায়ু অভিবাসীদের গ্রহণকারী শহর ও শহরতলী এলাকায় সামাজিক সংহতি, সম্পদ ভাগাভাগি এবং ন্যায়সঙ্গত সেবা অ্যাক্সেস শক্তিশালী করার কার্যক্রম।',
      'জলবায়ু গতিশীলতার ওপর regional অ্যাডভোকেসি — দক্ষিণ এশীয় এবং এশিয়া প্যাসিফিক ফোরামে বাংলাদেশের জলবায়ু বাস্তুচ্যুতি সংকট তুলে ধরা, জলবায়ু গতিশীলতা এবং শরণার্থী সুরক্ষার জন্য একটি জাস্ট আঞ্চলিক কাঠামোর পক্ষে ওকালতি করা।',
    ],
  },
  {
    id: 'knowledge-centers',
    title: 'Knowledge Centers, Libraries & Community Learning',
    title_bn: 'জ্ঞান কেন্দ্র, গ্রন্থাগার ও সামাজিক শিক্ষা',
    icon: BookOpen,
    theme: 'Knowledge',
    theme_bn: 'জ্ঞান',
    color: '#1565C0',
    bg: '#E3F2FD',
    description: "Access to knowledge is a fundamental right and a prerequisite for climate resilience. YCN establishes and supports community knowledge centers and libraries that serve as local hubs for learning, information, digital access, and civic engagement — directly inspired by BRAC's nationally transformative community library and learning center model.",
    description_bn: 'জ্ঞানের অ্যাক্সেস একটি মৌলিক অধিকার এবং জলবায়ু সহনশীলতার একটি পূর্বশর্ত। YCN সামাজিক জ্ঞান কেন্দ্র এবং পাঠাগার স্থাপন ও সমর্থন করে যা শেখা, তথ্য, ডিজিটাল অ্যাক্সেস এবং নাগরিক সম্পৃক্ততার জন্য স্থানীয় হাব হিসেবে কাজ করে — যা সরাসরি ব্র্যাকের (BRAC) জাতীয়ভাবে রূপান্তরমূলক সামাজিক লাইব্রেরি এবং লার্নিং সেন্টার মডেল দ্বারা অনুপ্রাণিত।',
    keyPrograms: [
      'Community Climate Libraries — Establishing community reading rooms and resource centers stocked with books, periodicals, and educational materials on climate, environment, health, livelihoods, and rights in both Bangla and English.',
      'Digital Access Centers — Providing computers, tablets, and internet connectivity in rural and peri-urban areas for digital literacy, e-learning, and access to online government services.',
      'Climate Information Kiosks — Local weather, flood early warning, agricultural advisory, and government scheme information disseminated through community kiosks and public notice boards.',
      'Youth Study Circles — Regular facilitated discussion and peer-learning groups for young people to explore climate science, civic issues, and sustainable development topics.',
      'Community Radio & Local Media — Supporting community radio programming and local media production on climate, health, rights, livelihoods, and development topics in local dialects.',
    ],
    keyPrograms_bn: [
      'সামাজিক জলবায়ু লাইব্রেরি — বাংলা এবং ইংরেজি উভয় ভাষায় জলবায়ু, পরিবেশ, স্বাস্থ্য, জীবিকা এবং অধিকার সম্পর্কিত বই, সাময়িকী এবং শিক্ষামূলক উপকরণে সমৃদ্ধ সামাজিক পাঠাগার এবং তথ্য কেন্দ্র স্থাপন।',
      'ডিজিটাল অ্যাক্সেস সেন্টার — ডিজিটাল সাক্ষরতা, ই-লার্নিং এবং অনলাইন সরকারি পরিষেবাগুলোতে অ্যাক্সেসের জন্য গ্রামীণ ও শহরতলী এলাকায় কম্পিউটার, ট্যাবলেট এবং ইন্টারনেট সংযোগ প্রদান।',
      'জলবায়ু তথ্য কিয়স্ক — সামাজিক কিয়স্ক এবং পাবলিক নোটিশ বোর্ডের মাধ্যমে প্রচারিত স্থানীয় আবহাওয়া, বন্যার প্রাথমিক সতর্কতা, কৃষি পরামর্শ এবং সরকারি প্রকল্পের তথ্য।',
      'যুব স্টাডি সার্কেল — তরুণদের জলবায়ু বিজ্ঞান, নাগরিক সমস্যা এবং টেকসই উন্নয়ন বিষয়গুলো অন্বেষণ করার জন্য নিয়মিত সুবিধাজনক আলোচনা এবং সমকক্ষ-শিক্ষা গ্রুপ।',
      'কমিউনিটি রেডিও ও স্থানীয় মিডিয়া — স্থানীয় উপভাষায় জলবায়ু, স্বাস্থ্য, অধিকার, জীবিকা এবং উন্নয়নমূলক বিষয়ে কমুনিটি রেডিও প্রোগ্রামিং এবং স্থানীয় মিডিয়া প্রযোজনায় সহায়তা করা।',
    ],
  },
  {
    id: 'biodiversity',
    title: 'Biodiversity in Action',
    title_bn: 'জীববৈচিত্র্য সংরক্ষণে পদক্ষেপ',
    icon: TreePine,
    theme: 'Biodiversity',
    theme_bn: 'জীববৈচিত্র্য',
    color: '#33691E',
    bg: '#F1F8E9',
    description: 'Protecting natural habitats, large-scale afforestation, and preserving biodiversity.',
    description_bn: 'প্রাকৃতিক আবাসস্থল রক্ষা, বৃহত্তর বনায়ন এবং জীববৈচিত্র্য সংরক্ষণ।',
    keyPrograms: [
      'Community-led Biodiversity Monitoring — Establishing local committees to track and protect vulnerable plant and animal species.',
      'Reforestation Initiatives — Partnering with local authorities to restore degraded forests using native species.',
      'Environmental Education for Youth — Workshops on the importance of local ecosystems and conservation.'
    ],
    keyPrograms_bn: [
      'সম্প্রদায়-নেতৃত্বাধীন জীববৈচিত্র্য পর্যবেক্ষণ — দুর্বল উদ্ভিদ এবং প্রাণীর প্রজাতি ট্র্যাক এবং সুরক্ষার জন্য স্থানীয় কমিটি গঠন।',
      'বনায়ন উদ্যোগ — দেশীয় প্রজাতি ব্যবহার করে ক্ষয়প্রাপ্ত বন পুনরুদ্ধারের জন্য স্থানীয় কর্তৃপক্ষের সাথে অংশীদারিত্ব।',
      'যুবকদের জন্য পরিবেশগত শিক্ষা — স্থানীয় বাস্তুতন্ত্র এবং সংরক্ষণের গুরুত্ব নিয়ে কর্মশালা।'
    ],
  },
  {
    id: 'wildlife',
    title: 'Wildlife & Welfare',
    title_bn: 'বন্যপ্রাণী ও কল্যাণ',
    icon: Bird,
    theme: 'Wildlife',
    theme_bn: 'বন্যপ্রাণী',
    color: '#827717',
    bg: '#F9FBE7',
    description: 'Protecting endangered species and ensuring welfare for wildlife in climate-vulnerable zones.',
    description_bn: 'বিপন্ন প্রজাতি রক্ষা এবং জলবায়ু-ঝুঁকিপূর্ণ অঞ্চলে বন্যপ্রাণীর কল্যাণ নিশ্চিত করা।',
    keyPrograms: [
      'Anti-Poaching Campaigns — Raising awareness and working with local authorities to stop illegal hunting.',
      'Wildlife Rescue & Rehabilitation — Providing support for injured or displaced wildlife due to extreme weather.',
      'Habitat Preservation — Securing vital corridors and breeding grounds for endangered species.'
    ],
    keyPrograms_bn: [
      'শিকার বিরোধী অভিযান — সচেতনতা বৃদ্ধি এবং অবৈধ শিকার বন্ধ করতে স্থানীয় কর্তৃপক্ষের সাথে কাজ করা।',
      'বন্যপ্রাণী উদ্ধার ও পুনর্বাসন — চরম আবহাওয়ার কারণে আহত বা বাস্তুচ্যুত বন্যপ্রাণীদের সহায়তা প্রদান।',
      'আবাসস্থল সংরক্ষণ — বিপন্ন প্রজাতির জন্য গুরুত্বপূর্ণ করিডোর এবং প্রজনন স্থল সুরক্ষিত করা।'
    ],
  },
  {
    id: 'mental-health',
    title: 'Mental Health & Psychosocial Support',
    title_bn: 'মানসিক স্বাস্থ্য ও মনস্তাত্ত্বিক সহায়তা',
    icon: Brain,
    theme: 'Mental Health',
    theme_bn: 'মানসিক স্বাস্থ্য',
    color: '#00695C',
    bg: '#E0F2F1',
    description: 'Connecting survivors to psychosocial support and specialized climate-anxiety care.',
    description_bn: 'মানসিক স্বাস্থ্য সহায়তা এবং বিশেষায়িত জলবায়ু-উদ্বেগ সেবার সাথে ক্ষতিগ্রস্তদের সংযুক্ত করা।',
    keyPrograms: [
      'Climate Anxiety Counseling — Offering specialized support groups for youth experiencing eco-anxiety.',
      'Disaster Trauma Recovery — Deploying psychological first aid to communities affected by severe weather events.',
      'Community Wellbeing Workshops — Building emotional resilience and strong support networks in vulnerable areas.'
    ],
    keyPrograms_bn: [
      'জলবায়ু উদ্বেগ কাউন্সেলিং — ইকো-অ্যাংজাইটি বা পরিবেশগত উদ্বেগ অনুভবকারী তরুণদের জন্য বিশেষ সহায়তা গ্রুপ।',
      'দুর্যোগ ট্রমা পুনরুদ্ধার — মারাত্মক আবহাওয়ার ঘটনা দ্বারা ক্ষতিগ্রস্ত সম্প্রদায়গুলোতে মনস্তাত্ত্বিক প্রাথমিক চিকিৎসা মোতায়েন করা।',
      'কমিউনিটি ওয়েলবিয়িং ওয়ার্কশপ — ঝুঁকিপূর্ণ এলাকায় মানসিক স্থিতিস্থাপকতা এবং শক্তিশালী সহায়তা নেটওয়ার্ক তৈরি করা।'
    ],
  },
  {
    id: 'coastal-marine',
    title: 'Coastal & Marine Ecosystem Protection',
    title_bn: 'উপকূলীয় এবং সামুদ্রিক ইকোসিস্টেম সুরক্ষা',
    icon: Waves,
    theme: 'Coastal & Marine',
    theme_bn: 'উপকূলীয় ও সামুদ্রিক',
    color: '#0277BD',
    bg: '#E1F5FE',
    description: 'Restoring mangrove forests and protecting fragile coastlines from cyclones and tidal surges.',
    description_bn: 'ম্যানগ্রোভ বন পুনরুদ্ধার এবং ঘূর্ণিঝড় ও জলোচ্ছ্বাস থেকে ভঙ্গুর উপকূলরেখা রক্ষা করা।',
    keyPrograms: [
      'Mangrove Afforestation — Planting mangroves to serve as natural barriers against storm surges.',
      'Marine Debris Cleanup — Organizing regular coastal cleanups to reduce plastic pollution in the ocean.',
      'Sustainable Fishing Advocacy — Working with local fishing communities to promote eco-friendly practices.'
    ],
    keyPrograms_bn: [
      'ম্যানগ্রোভ বনায়ন — জলোচ্ছ্বাসের বিরুদ্ধে প্রাকৃতিক বাধা হিসেবে কাজ করার জন্য ম্যানগ্রোভ রোপণ।',
      'সামুদ্রিক ধ্বংসাবশেষ পরিষ্কার — মহাসাগরে প্লাস্টিক দূষণ কমাতে নিয়মিত উপকূলীয় পরিচ্ছন্নতা অভিযানের আয়োজন।',
      'টেকসই মৎস্য অ্যাডভোকেসি — পরিবেশবান্ধব অনুশীলন প্রচারের জন্য স্থানীয় মৎস্যজীবী সম্প্রদায়ের সাথে কাজ করা।'
    ],
  },
  {
    id: 'urban-climate',
    title: 'Urban Climate Resilience',
    title_bn: 'শহুরে জলবায়ু স্থিতিস্থাপকতা',
    icon: Building2,
    theme: 'Urban Resilience',
    theme_bn: 'শহুরে স্থিতিস্থাপকতা',
    color: '#EF6C00',
    bg: '#FFF3E0',
    description: 'Building resilience against urban flooding, heat stress, and infrastructure strain in cities.',
    description_bn: 'শহরাঞ্চলে বন্যা, তাপের চাপ এবং অবকাঠামোগত চাপের বিরুদ্ধে সহনশীলতা তৈরি করা।',
    keyPrograms: [
      'Urban Heat Island Mitigation — Promoting green roofs, urban tree planting, and cool pavements.',
      'Flood Resilience Infrastructure — Advocating for improved drainage and permeable surfaces to manage heavy rainfall.',
      'Sustainable Urban Planning — Partnering with city planners to integrate climate resilience into urban development.'
    ],
    keyPrograms_bn: [
      'আরবান হিট আইল্যান্ড প্রশমন — সবুজ ছাদ, শহুরে বৃক্ষরোপণ এবং শীতল ফুটপাথ প্রচার করা।',
      'বন্যা স্থিতিস্থাপকতা অবকাঠামো — ভারী বৃষ্টিপাত পরিচালনার জন্য উন্নত নিষ্কাশন এবং ব্যাপ্ত পৃষ্ঠের পক্ষে ওকালতি করা।',
      'টেকসই নগর পরিকল্পনা — নগর উন্নয়নে জলবায়ু স্থিতিস্থাপকতা সংহত করার জন্য নগর পরিকল্পনাবিদদের সাথে অংশীদারিত্ব।'
    ],
  }
];
